id: P43543B43
initial_creation_type: input
source_metadata:
  title: Fifth Shamarpa
  language: en
  description: 'Texts by and about the Fifth Shamarpa, Könchok Yenlak (dkon mchog
    yan lag, 1525–1583):'
  volume:
    c69bc4faffba4352a02f79e1f982b8b0:
      title: A Song of Calling the Guru from Afar
      parent: Prayers
created_at: '2022-02-28T23:15:32.571087'
last_modified_at: '2022-02-28T23:15:32.571094'
